version: '3'
services:
  web:
    image: caddy/caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - YOUR_EMAIL: [YOUR_EMAIL]
      - HOST: [HOST]
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy-root-home:/root
    deploy:
      replicas: 1
    restart: always
    depends_on:
      - v2ray
  v2ray:
    image: v2ray/offical
    configs:
      - source: v2ray-server
        target: /etc/v2ray/config.json
    deploy:
      replicas: 1
    restart: always
    depends_on:
      - ntpd
  ntpd:
    image: abreto/ntpd
    cap_add:
      - SYS_TIME
      - SYS_NICE
    restart: always
    deploy:
      mode: global
    configs:
      - source: ntpd
        target: /etc/ntpd.conf

configs:
  caddyfile:
    file: ./Caddyfile
  v2ray-server:
    file: ./config.server.json
  ntpd:
    file: ./ntpd.conf

volumes:
  caddy-root-home:

networks:
  default:
    driver: overlay
